apiVersion: v1
kind: PersistentVolume
metadata:
  name: lotse-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-lotse-storage
  local:
    path: /run/desktop/mnt/host/c/ProgramData/Kubernetes/Lotse/lotse-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lotse-data-pvc
  namespace: lotse
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-lotse-storage
  resources:
    requests:
      storage: 10Gi
