package_name: "hello_world"
entrypoint: main.py
version: 1.0.12
description: "Hello World script"
python_version: 3.8.10
args:
  - name: "name"
    defaultvalue: "vince"
environment:
  - name: "AGE"
    value: "32"